[tool.poetry]
    authors     = ["Mads Hvelplund <mhvelplund@users.noreply.github.com>"]
    description = "Rename images based on their folder"
    name        = "imgmv"
    readme      = "README.md"
    version     = "0.1.0"

[tool.poetry.dependencies]
    python = "^3.11"

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry-core"]

[tool.poetry.scripts]
    imgmv = "imgmv.main:run"
