[tool.poetry]
    authors     = ["Mads Hvelplund <mhvelplund@users.noreply.github.com>"]
    description = "Rename images based on their folder."
    name        = "imgmv"
    readme      = "README.md"
    version     = "0.1.2"

[tool.poetry.dependencies]
    python = "^3.11"

[tool.poetry.group.dev.dependencies]
    pytest = ">=8.3.4,<10.0.0"
    ruff   = "^0.9.6"

[build-system]
    build-backend = "poetry.core.masonry.api"
    requires      = ["poetry-core"]

[tool.poetry.scripts]
    imgmv = "imgmv.main:run"
